config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :orders, only: %i[create]
    post '/trade', to: "orders#trade", as: :trade
  end
  resources :users, only: %i[show]
  resources :orders, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :orders
  has_many :buyers, through: :orders, source: :user
  validates_presence_of :name, on: :create, message: "can't be blank"
  validates :coin_price, on: :create, presence: true, numericality: { other_than: 0, message: "can't be zero" } 
  validates :quantity, on: :create, presence: true, numericality: { other_than: 0, message: "can't be zero" }
  
  has_one_attached :photo


  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:name, :description],
    using: {
      tsearch: {prefix: true}
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :bought_products, through: :orders, source: :products
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :coins])

    # devise_parameter_sanitizer.permit(:account_update, keys: [:coins])

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    order = Order.new(order_params)
    order.user = current_user
    order.product = product
    price = product.coin_price * order.quantity
    if product.quantity < order.quantity
      flash[:alert] = "You can't buy this much #{product.name}"
      redirect_to products_path(product)
    else
      if price > current_user.coins
        flash[:alert] = "Not enough coins to buy this item."
        redirect_to products_path(product)
      else
        order.save
        current_user.coins -= price
        current_user.save
        product.user.coins += price
        product.user.save
        product.quantity -= order.quantity
        new_product = current_user.products.find_by name: product.name
        if new_product.nil?
          new_product = Product.new name: product.name, coin_price: product.coin_price, description: product.description, user: current_user
        else
          new_product.quantity += order.quantity
        end
        new_product.save
        product.save
        redirect_to user_path(current_user), notice: "Congratulations: It's yours. Now, please edit your new product price."
      end
    end
  end

  def trade
    seller_product = Product.find(params[:product_id])
    order = Order.new user: current_user, product: seller_product, quantity: 1, tradable: seller_product.tradable_for
    buyer_product = current_user.products.find_by name: order.tradable

    if seller_product.quantity <= 0
      flash[:alert] = "There is no #{seller_product.name} available at the moment. :( "
      redirect_to products_path(seller_product)
    elsif buyer_product.quantity <= 0
      flash[:alert] = "You have no #{buyer_product.name} available at the moment. :( "
      redirect_to products_path(seller_product)
    else
      buyer_new_product = current_user.products.find_by name: seller_product.name
      if buyer_new_product.nil?
        buyer_new_product = Product.new name: seller_product.name, coin_price: seller_product.coin_price, description: seller_product.description, user: current_user, quantity: 1
      else
        buyer_new_product.quantity += 1
      end
      seller_new_product = seller_product.user.products.find_by name: buyer_product.name
      if seller_new_product.nil?
        seller_new_product = Product.new name: buyer_product.name, coin_price: buyer_product.coin_price, description: buyer_product.description, user: seller_product.user, quantity: 1
      else
        seller_new_product.quantity += 1
      end
      seller_product.quantity -= 1
      buyer_product.quantity -= 1
      seller_product.save
      seller_new_product.save
      buyer_product.save
      buyer_new_product.save
      redirect_to user_path(current_user), notice: "Trade was successful! Now, please edit your new product's price."
    end
  end

  def order_params
    params.require(:order).permit(:quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home products]
  def home
    @products = Product.all.size > 15 ? Product.all[-15..Product.all.size] : Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy trade]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @products = Product.all

    if params[:query].present?
      @products = @products.global_search(params[:query])
    end
  end

  def show
    @order = Order.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.name = @product.name.capitalize
    @product.category = @product.category.capitalize
    @product.tradable_for = @product.tradable_for.capitalize
    existing_product = current_user.products.find_by name: @product.name
    if existing_product
      redirect_to edit_product_path(existing_product), alert: "You already have #{existing_product.name}. If you want to add more, please add on product edition page"
    else
      @product.save
      if @product.save
        redirect_to user_path(current_user), notice: 'Product created'
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    @product.update(product_params)
    @product.name = @product.name.capitalize
    @product.category = @product.category.capitalize
    @product.tradable_for = @product.tradable_for.capitalize
    @product.save
    redirect_to product_path(@product)
  end

  def destroy # rever se queremos que o usuário posso deletar produtos
    @product.destroy
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :quantity, :category, :coin_price, :tradable_for, :photo)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_action :set_user, only: %i[show my_items edit update ]

  def show
    @products = Product.order(:name).where(user: @user)
  end
  
  def my_items
    # check set_user method
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User updated"
    else
      render :edit
    end
  end

  # def create
  #   @user = User.new(use_params)

  #   if @user.save
  #     redirect_to @user, notice: 'Welcome'
  #   else
  #     render :new, notice: 'Please review pending fields'
  #   end
  # end

  # def destroy
  #   @user.destroy
  # end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :avatar, :coins, :username)
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medieval Market</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <div class="container">
      <div class="navbar-custom">
        <%= link_to root_path do %>
          <%= image_tag "logo.png", class: "logo" %>
        <% end %>
        <p>
          <% if user_signed_in? %>
          <strong><%= link_to "#{current_user.username}", user_path(current_user) %></strong>  |
          <i class="fas fa-coins" style="color: #e9a003;"></i> <%= current_user.coins %>  |
          <%= link_to 'Sell', new_product_path %>  |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Log in", new_user_session_path, :class => 'navbar-link'  %> |
          <%= link_to 'Sell something', new_product_path %>
        <% end %>
      </p>
      </div>
    </div>

    <div class="minimal">
    <%= yield %>
    </div>

    <div class="footer">
      <div class="row align-items-center justify-content-center">
      <a href="#"><i class="fab fa-github mr-4"></i></a>
      <a href="#"><i  class="fab fa-facebook mr-4"></i></a>
      <a href=""><i class="fas fa-crown"></i></a>
      </div>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
  <div class="topo">

    <div class="batata">
      <%= form_tag products_path, method: :get do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search a product here"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>

  </div>

<div class="container">



  <div class="pl-0 pt-5" style="font-family: 'Roboto', sans-serif; font-weight: 900; font-size: 25px; line-height: 41px; color: #313131; margin-top: -20px;">
    <p>Featured</p>
  </div>

  <div class="row d-flex justify-content-space-around mb-5">
  <% @products.each do |product| %>
    <div class="card text-center col-2 m-3 w-100 pr-0 pl-0 border-white">
      <%= link_to  product_path(product) do %>
        <% if product.photo.attached? %>
          <%= cl_image_tag product.photo.key, class:"figure", height: 125, width: 190,:fetch_format=>:auto, crop: :fill %>
        <% else %>
          <%= image_tag "placeholder.png", class:"card-img-top" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title" style="font-family: 'Roboto', sans-serif; font-weight: 700; font-size: 18px;"><%= product.name %></h5>
          <p class="card-text" style="font-family: 'Roboto', sans-serif; font-weight: 400; font-size: 16px;"><i class="fas fa-coins" style="color: #e9a003;"></i>

  <%= product.coin_price%>
          </p>
        </div>
      <% end %>
    </div>
  <% end %>

    </div>

  </div>

</div>

app/views/products/_edit.html.erb
<div class="container col-4 mt-5 mb-5">
  <div class="row justify-content-center mb-3">
  <h3>Edit <%= @product.name %></h3>
  </div>
    <%= simple_form_for(product) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :quantity, input_html: { min: 1 }  %>
    <%= f.input :coin_price, input_html: { min: 1 }  %>
    <%= f.input :category %>
    <%= f.input :tradable_for %>
    <%= f.input :photo, as: :file %>
    <br>
    <div class="row justify-content-center">
      <button type="button" class="btn btn-light"><%= f.button :submit %></button>
    </div>
  <% end %>
</div>

<%#= add the line below to link to this partial %>
<%#= render 'products/edit', user: current_user, product: @product  %>

app/views/products/edit.html.erb
<div class="container">
  <h3>Edit <%= @product.name %>:</h3>
  <%= simple_form_for(@product) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :quantity, input_html: { min: 1 }  %>
    <%= f.input :coin_price, input_html: { min: 1 }  %>
    <%= f.input :category %>
    <%= f.input :tradable_for %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/products/index.html.erb
  <div class="topo">

    <div class="batata">
      <%= form_tag products_path, method: :get do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search a product here"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>

  </div>

<div class="container">

  <div class="pl-0 pt-5" style="font-family: 'Roboto', sans-serif; font-weight: 900; font-size: 25px; line-height: 41px; color: #313131; margin-top: -20px;">
    <p>Products</p>
  </div>

  <div class="row d-flex justify-content-space-around">
    <% @products.each do |product| %>
      <% if product.quantity > 0 %>
        <div class="card text-center col-2 m-3 w-100 pr-0 pl-0 border-white">
          <%= link_to  product_path(product) do %>
            <% if product.photo.attached? %>
          <%= cl_image_tag product.photo.key, class:"figure", height: 125, width: 190, :fetch_format=>:auto, crop: :fill %>
            <% else %>
              <%= image_tag "placeholder.png", class:"card-img-top" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title" style="font-family: 'Roboto', sans-serif; font-weight: 700; font-size: 18px;"><%= product.name %></h5>
              <p class="card-text" style="font-family: 'Roboto', sans-serif; font-weight: 400; font-size: 16px;"><i class="fas fa-coins" style="color: #e9a003;"></i> <%= product.coin_price %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/products/new.html.erb
<div class="container">
  <div class="pl-0 pt-5 mt-3 pb-4 d-flex justify-content-center" style="font-family: 'Roboto', sans-serif; font-weight: 900; font-size: 25px; line-height: 41px; color: #313131;">
    <p>Create new product</p>
  </div>
  <div class="container d-flex justify-content-center">
    <div class="row d-flex justify-content-space-around">
      <%= simple_form_for(@product) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :quantity, input_html: { min: 1 } %>
        <%= f.input :coin_price, input_html: { min: 1 } %>
        <%= f.input :category %>
        <%= f.input :tradable_for %>
        <%= f.input :photo, as: :file %>
        <div class="row justify-content-center mt-4 mb-5">
          <%= f.submit class:"btn btn-primary btn-md" %>
        </div>
      <% end %>
    </div>
    <br>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">

<div class="col s3" style="margin-left: -10px; margin-bottom: 20px;">
<%= link_to 'Back to all products', products_path %></li>
</div>

<div class="row">

    <% if current_user %>
      <% if @product.user != current_user && @product.quantity > 0 %>
        <% if @product.quantity > 0 %>

      <div class="col s3 offset-md-1">
          <div class="imagebox" style="margin-left: -100px; margin-bottom: 50px;">
            <% if @product.photo.attached? %>
              <%= cl_image_tag @product.photo.key, height: 400, width: 400,:fetch_format=>:auto, crop: :fill %>
            <% else %>
              <%= image_tag "placeholder.png", class:"card-img-top" %>
            <% end %>
            <h1 style="margin-top: 25px;"><strong>About this product</strong></h1><p><%= @product.description if @product.description %></p>
          </div>
      </div>

<div class="col s9" style="margin-top: 50px; margin-right: 420px;">

<div class="container" style="font-family: 'Roboto', sans-serif; margin-top: -50px;">
        <h2><%= @product.name %></h2>
    <p style="font-family: 'Roboto', sans-serif;">By <%= link_to @product.user.username, user_path(@product.user) %></p>

    <div class="product-specs">
      <p><strong>Category:</strong> <%= @product.category%></p>
      <p><strong># Available:</strong> <%= @product.quantity%></p>
      <br>
    </div>
      <p style="font-family: 'Roboto', sans-serif; font-size: 20px;"><i class="fas fa-coins" style="color: #e9a003;"></i> <%= @product.coin_price%> coins</p>
      <% else %>
      <p>Product not avaliable</p>
    <% end %>

            <%= simple_form_for [@product, @order] do |f| %>
            <div class="quantidade">
              <%= f.input :quantity, input_html: { min: 1, max: @product.quantity } %>
            </div>
            <br>
              <%= f.button :submit, class:"btn btn-primary btn-md mb-1" %>
            <% end %>
            <% if current_user.products.find_by name: @product.tradable_for %>
              <p>Or <strong><%= link_to 'trade it', product_trade_path(@product), method: :post %></strong> with your <%= @product.tradable_for %></p>

            <% end %>
        <% elsif @product.user == current_user %>
          <%= render 'products/edit', user: current_user, product: @product  %>
      <% end %>
    <% else %>

<!-- Aqui mostramos as infos do produto para quem estiver deslogado -->

      <% if @product.quantity > 0 %>

        <div class="col s3 offset-md-1">
            <div class="imagebox" style="margin-left: -100px; margin-bottom: 50px;">
              <% if @product.photo.attached? %>
                <%= cl_image_tag @product.photo.key, height: 400, width: 400,:fetch_format=>:auto, crop: :fill %>
              <% else %>
                 <%= image_tag "placeholder.png", class:"card-img-top" %>
              <% end %>
              <h1><strong>About this product</strong></h1><p><%= @product.description if @product.description %></p>
            </div>
        </div>

        <div class="col s9" style="margin-top: 50px; margin-right: 420px;">

          <div class="container" style="margin-top: -50px;">
            <h2><%= @product.name %></h2>
            <p style="font-family: 'Roboto';">By <%= link_to @product.user.username, user_path(@product.user) %></p>

            <div class="product-specs">
              <p><strong>Category:</strong> <%= @product.category%></p>
              <p><strong># Available:</strong> <%= @product.quantity%></p>
              <br>
            </div>
              <p style="font-family: 'Roboto', sans-serif; font-size: 20px;"><i class="fas fa-coins" style="color: #e9a003;"></i> <%= @product.coin_price%> coins</p>

      <% else %>

              <p>Product not avaliable</p>
              <% end %>
              </div>
        </div>

    <% end %>
    </div>
  </div>
</div>

<div class="container" style="margin-top: 100px;">
<p style="color: white">ffff</p>
  </div>

app/views/shared/_edit.html.erb
<div class="container">
  <%= simple_form_for(product) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :quantity %>
    <%= f.input :coin_price %>
    <%= f.input :category %>
    <%= f.button :submit %>
  <% end %>
</div>

<%#= add the line below to link to this partial %>
<%#= render 'shared/new', user: current_user, product: @product  %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_recent_products.html.erb
  <% @products.each do |product| %>
    <% if product.quantity > 0 %>
      <div class="card text-center col-2 m-3 w-100 pr-0 pl-0 border-white">
        <img class="card-img-top" src="assets/placeholder.png" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title" style="font-family: 'Roboto', sans-serif; font-weight: 700; font-size: 18px;"><%= product.name %></h5>
          <p class="card-text" style="font-family: 'Roboto', sans-serif; font-weight: 400; font-size: 16px;"><%= product.coin_price %></p>
        </div>
      </div>
    <% end %>
  <% end %>

  
<%#= add the line below to link to this partial %>
<%#= render 'shared/recent_products' %>

app/views/users/_my_items.html.erb
<table class="table">
  <thead>
    <th style="font-family: 'Roboto', sans-serif;">Product</th>
    <th style="font-family: 'Roboto', sans-serif;">Quantity</th>
    <% if @user == current_user %>
      <th>Action</th>
    <% end %>
  </thead>
  <% @products.each do |product| %>
    <% if product.quantity > 0 %>
      <tr>
        <td style="font-family: 'Roboto', sans-serif;"><%= link_to "#{product.name.capitalize}", product_path(product) %></td>
        <td><%= product.quantity %></td>
        <% if product.user == current_user %>
          <td>
            <div class="row justify-content-space-between">
              <%= link_to product_path(product), method: :delete,
              data: { confirm: "Delete item?" } do %>
                <i class="fa fa-trash d-flex justify-content-around pr-5"></i>
              <% end %>
              <%= link_to product_path(product) do %>
                <i class="fa fa-edit justify-content-around"></i>
              <% end %>
            </div>
          </td>
          <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/users/show.html.erb
<div class="container mt-5">

  <h2 style="font-family: 'Roboto', sans-serif; font-size: 25px; margin-bottom: 25px;">Available products for <%= @user.username %></h2>
  <%= render "users/my_items" %>
  <div class="row justify-content-left mb-5">
  <% if @user == current_user %>
  <button type="button" class="btn btn-light mr-3"><%= link_to 'Sell a product', new_product_path %></button>
  <% end %>
  <button type="button" class="btn btn-light"><%= link_to 'Back to Products', products_path%></button>
  </div>
</div>